# Numpy 

In [5]:
import numpy as np

## From List


In [6]:
x = np.array([1,2,3,4])

In [7]:
x

array([1, 2, 3, 4])

In [8]:
type(x)

numpy.ndarray

In [9]:
y = np.array(["a", "b", "c"])

In [10]:
y

array(['a', 'b', 'c'], dtype='<U1')

In [11]:
# All integers are converted to string
z = np.array([1,2,3,"a"])

In [12]:
z

array(['1', '2', '3', 'a'], dtype='<U11')

In [13]:
# All integers are converted to float
b = np.array([1,2,3,4.5])

In [14]:
b

array([1. , 2. , 3. , 4.5])

In [15]:
# Integers and float are converted to string
c = np.array([1,2,3,4.5,"2"])

In [16]:
c

array(['1', '2', '3', '4.5', '2'], dtype='<U32')

 ## Giving Type Manually

In [17]:

x = np.array([1,2,3,4.6])

In [18]:
x

array([1. , 2. , 3. , 4.6])

In [19]:
x = np.array(["5"], dtype = "int32")

In [20]:
x

array([5])

## Creating Array of Zeros

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros(10, dtype = str)

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

### Creating Multidimensional Array of Zeros

In [24]:
# Creating array of 3 rows and 4 columns

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.zeros([3,8,8])

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0

In [27]:
# Creates empty stings which is ""
np.zeros((1,2), dtype = str)

array([['', '']], dtype='<U1')

In [28]:
np.zeros((2,3), dtype= bool)

array([[False, False, False],
       [False, False, False]])

## Creating Array of Specified Element

In [29]:
np.full((4,5), 5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [30]:
np.full((4,5), "a")

array([['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a']], dtype='<U1')

In [31]:
np.full((4,5), "5.2")

array([['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2']], dtype='<U3')

## Creating Array Using Consecutive Numbers

In [32]:
# [0,12)
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [34]:
np.arange(12,2,-2)

array([12, 10,  8,  6,  4])

## Dividing Interval

 > Returns num evenly spaced samples, calculated over the interval [start, stop].

In [36]:
# it returns 50 points by default
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [37]:
np.linspace(1,2,num = 3)

array([1. , 1.5, 2. ])

In [38]:
np.linspace(1,2,num = 3, endpoint=False)

array([1.        , 1.33333333, 1.66666667])

## Specifiying Number

In [39]:
 # 30 points between 0 and 1
np.linspace(0, 1, 30)

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

In [40]:
# 30 points between 0 and 1
np.linspace(0, 1, 3)

array([0. , 0.5, 1. ])

In [41]:
np.linspace(1.5, 4.7, 3)

array([1.5, 3.1, 4.7])

## Creating Array from Normal Distribution

>(mean, std, array size)

In [42]:
np.random.normal(0, 1, (4,5))

array([[ 1.76571767,  0.21684836,  0.6490985 , -0.70980391, -0.65149395],
       [ 1.05283649, -0.96825283, -0.18676125, -0.27081709, -0.2492219 ],
       [ 1.86939984,  0.24712151, -0.57194563,  0.37580775, -0.54307636],
       [-0.15171636, -1.79551522, -0.21203958, -0.82247693,  1.13066736]])

In [43]:
np.random.normal(10, 1, (4,5))

array([[10.89495087,  9.97375609, 10.15515105,  9.31979835,  9.26297729],
       [ 8.42270136,  9.04267106, 10.10114221, 10.23463169, 10.48302464],
       [ 7.87101211, 11.85808407,  9.2630533 ,  8.93812548, 10.68023975],
       [10.6583454 , 11.21543098, 10.74597673,  8.51384652, 10.12994048]])

## Creating Array from Random Integers


>[low,high)

In [44]:
np.random.randint(1, 10, (3,4))

array([[7, 2, 9, 4],
       [6, 4, 7, 8],
       [4, 7, 1, 4]])

In [45]:
np.random.randint(1, 10, (3,5,5))

array([[[6, 9, 1, 4, 4],
        [2, 1, 5, 6, 4],
        [2, 4, 3, 1, 4],
        [4, 9, 3, 8, 3],
        [9, 7, 4, 2, 4]],

       [[3, 3, 6, 3, 4],
        [1, 5, 4, 5, 9],
        [9, 9, 4, 7, 6],
        [1, 5, 8, 8, 6],
        [4, 3, 1, 6, 2]],

       [[9, 5, 7, 3, 5],
        [8, 1, 2, 7, 4],
        [7, 4, 8, 6, 9],
        [5, 7, 6, 4, 8],
        [7, 8, 6, 3, 6]]])

In [46]:
np.random.randint(1, 2)

1

In [47]:
d = {}

for _ in range(20000):
    val = np.random.randint(1, 11)
    
    if val not in d:
        d[val] = 1
    else:
        d[val] += 1

In [48]:
d

{4: 2022,
 10: 2005,
 6: 1989,
 8: 2000,
 9: 2049,
 7: 1979,
 1: 2004,
 2: 2014,
 5: 1935,
 3: 2003}

## Creating Identity Array

In [49]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [50]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Numpy Array Operations

In [53]:
[2, 4, 8] * 3

[2, 4, 8, 2, 4, 8, 2, 4, 8]

In [54]:
[2, 4, 8] + [2, 4, 8] + [2, 4, 8]

[2, 4, 8, 2, 4, 8, 2, 4, 8]

In [55]:
x = np.array([1, 2, 3])
y = np.array([2, 4, 8])


x * y

array([ 2,  8, 24])

In [56]:
z = x * y

In [57]:
z

array([ 2,  8, 24])

In [58]:
a = [1, 2, 3]
b = [2, 4, 8]

In [59]:
a + b # concat for python list


[1, 2, 3, 2, 4, 8]

In [60]:
3 * a

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [61]:
x = x * 3

In [62]:
x

array([3, 6, 9])

### Shape

In [63]:
x = np.zeros((2,3))
             
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [64]:
y = np.zeros((2,5,4))
             
print(y)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [65]:
x.shape

(2, 3)

In [66]:
y.shape

(2, 5, 4)

### ndim

In [67]:
x = np.zeros((2,3))

print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [68]:
y = np.zeros((2,5,4))
             
print(y)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [69]:
x.ndim

2

In [70]:
y.ndim

3

### Size

In [71]:
x = np.zeros((2,3))
             
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [72]:
y = np.zeros((2,5,4))
             
print(y)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [73]:
x.size


6

In [74]:
y.size

40

### Dtype

In [75]:
x = np.zeros((2,3))
             
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [76]:
x.dtype

dtype('float64')

### Reshaping

In [77]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
a.ndim

1

In [79]:
a.size

10

In [80]:
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [81]:
a.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [82]:
c = a.reshape((2,5))

In [83]:
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [84]:
c.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [85]:
c.reshape(1, 10).shape

(1, 10)

## Vector to Matrix

In [86]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
a.size

10

In [88]:

a.ndim

1

In [89]:
# It is a vector
a.shape

(10,)

In [90]:
a.reshape(1, 2, 1,  -1)

array([[[[ 1,  2,  3,  4,  5]],

        [[ 6,  7,  8,  9, 10]]]])

In [91]:
# It is a matrix now
b = a.reshape(1, a.size)
print(b)

[[ 1  2  3  4  5  6  7  8  9 10]]


In [92]:
b = a.reshape(1, -1)


In [93]:
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [94]:
a.reshape(1, a.size).ndim

2

In [95]:
a.reshape(a.size, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [96]:
# second way

a[np.newaxis, :]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [97]:
a[np.newaxis, :]


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [98]:
a[np.newaxis, :].shape

(1, 10)

In [99]:
# column vector

a[:, np.newaxis]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [100]:
a[:, np.newaxis].shape

(10, 1)

In [101]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [102]:
a[None,:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [103]:
a[:, None]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

## Concatenation

In [104]:
a = np.array([1, 2, 3, 4])

In [105]:
b = np.array([5, 6, 7, 8])

In [106]:
# does not modify a and b
np.concatenate([a, b])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [107]:
l = [10, 11]

In [108]:
np.concatenate([a, b, l])

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11])

In [109]:
a

array([1, 2, 3, 4])

In [110]:
np.concatenate([a, a])

array([1, 2, 3, 4, 1, 2, 3, 4])

In [111]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])

In [112]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [113]:
np.concatenate([x, x])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [114]:
# keeping axis = 0 constant
np.concatenate([x, x], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## Stack

In [115]:
a = np.array([1,2,3])

In [116]:
a

array([1, 2, 3])

In [117]:
a.size

3

In [118]:
a.shape

(3,)

In [119]:
a.ndim

1

In [120]:
b = np.array([[4, 5, 6],
               [7, 8, 9]])

In [121]:
b

array([[4, 5, 6],
       [7, 8, 9]])

In [122]:
b.ndim

2

In [123]:
a[None, :]


array([[1, 2, 3]])

In [124]:
a[None, :].shape

(1, 3)

In [125]:
np.concatenate([a[None, :],b])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [126]:
# their column number matches
np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [127]:
# their row number matches
a = np.array([[1],
              [2]])

In [128]:
a

array([[1],
       [2]])

In [129]:
b

array([[4, 5, 6],
       [7, 8, 9]])

In [130]:
np.concatenate([a, b], axis = 1)

array([[1, 4, 5, 6],
       [2, 7, 8, 9]])

In [131]:
np.hstack([a,b]) # change

array([[1, 4, 5, 6],
       [2, 7, 8, 9]])

### Stacking is the same as adding new axis then concatenating on that axis

In [132]:
a = np.array([1,2,3])

In [133]:
b = np.array([[4, 5, 6],
               [7, 8, 9]])

In [134]:
a = a.reshape(1,3)

In [135]:
a

array([[1, 2, 3]])

In [136]:
np.concatenate([a,b])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [137]:
# their row number matches
a = np.array([[1],
              [2]])

In [138]:
a

array([[1],
       [2]])

In [139]:
b

array([[4, 5, 6],
       [7, 8, 9]])

In [140]:
b.shape

(2, 3)

In [141]:
a.shape

(2, 1)

In [142]:
np.concatenate([a,b], axis=1)

array([[1, 4, 5, 6],
       [2, 7, 8, 9]])

## Splitting

In [143]:

l = [10, 20, 30, 40, 50, 60, 70, 80]

In [144]:
l

[10, 20, 30, 40, 50, 60, 70, 80]

In [145]:
# [0,1], [2,3,4,5], [6,7]
np.split(l, [2,6])

[array([10, 20]), array([30, 40, 50, 60]), array([70, 80])]

In [146]:
np.split(l, [3,5])

[array([10, 20, 30]), array([40, 50]), array([60, 70, 80])]

## Assigning Multiple Variables 

In [148]:
a , b = (1, 10)

In [149]:
a

1

In [150]:
b

10

In [151]:

x, y, z = np.split(l, [2,6])

In [152]:
print(x)
print(y)
print(z)

[10 20]
[30 40 50 60]
[70 80]


### vsplit

In [153]:
a = np.arange(20).reshape(2,10)

In [154]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [155]:
np.vsplit(a, [1])

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])]

In [156]:
np.vsplit(a, [1])[0]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

### hsplit

In [157]:
a = np.arange(20).reshape(2,10)

In [158]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [159]:
np.hsplit(a, [2])

[array([[ 0,  1],
        [10, 11]]),
 array([[ 2,  3,  4,  5,  6,  7,  8,  9],
        [12, 13, 14, 15, 16, 17, 18, 19]])]

In [160]:
np.hsplit(a, [2])[1]

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [12, 13, 14, 15, 16, 17, 18, 19]])

In [161]:
np.hsplit(a, [2])[1].shape

(2, 8)

In [162]:
x, y = np.hsplit(a, [2])

In [163]:
x

array([[ 0,  1],
       [10, 11]])

In [164]:
y

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [12, 13, 14, 15, 16, 17, 18, 19]])

In [165]:
z

array([70, 80])

In [166]:
x, y, z = np.hsplit(a, [2,4])

In [167]:
z

array([[ 4,  5,  6,  7,  8,  9],
       [14, 15, 16, 17, 18, 19]])

## Sorting

In [168]:
a = np.array([20,32,5,30,10])

In [169]:
np.sort(a)

array([ 5, 10, 20, 30, 32])

In [170]:
a

array([20, 32,  5, 30, 10])

In [171]:
# modifies the a
a.sort() # inplace(same as a = np.sort(a))

In [172]:
a

array([ 5, 10, 20, 30, 32])

### argsort

In [173]:
a = np.array([3,1,6,5,4,2])

In [174]:
# it retuns the indexes in increasing order
idxs = np.argsort(a)

In [175]:
idxs

array([1, 5, 0, 4, 3, 2], dtype=int64)

## Accessing Elements in Multidimensional Array

In [176]:
a = np.arange(1,21).reshape(4,5)

In [177]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [178]:
a[1]

array([ 6,  7,  8,  9, 10])

In [179]:
a[1][1]

7

In [180]:
a.ndim

2

In [181]:
a[0]

array([1, 2, 3, 4, 5])

In [182]:
a[0].ndim

1

In [183]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [184]:
a[1,1] = 10

In [185]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 10,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [186]:
# It converts it into array's dtype
a[1,1] = 20.40

In [187]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 20,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [188]:
a[1,1] = "30"

In [189]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 30,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## Slice Indexing

In [190]:
a = np.arange(1,21).reshape(4,5)

In [191]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [192]:
a[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [193]:
a[1::2]

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])

In [194]:
a[::2,3]

array([ 4, 14])

In [195]:
a[0,2:4]

array([3, 4])

In [196]:
a[::,:4]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

In [197]:
a = np.array([1,2,3,4,5,6,7,8])

In [198]:
idxs = [1,3,5]
a[idxs]

array([2, 4, 6])

In [199]:
a = np.arange(20).reshape(4,5)

In [200]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [201]:
idx1 = [1,3,2]

In [202]:
a[idx1]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14]])

In [203]:
idx1 = [1,3,2]

In [204]:
idx2 = [3,0,2]


In [205]:
a[idx1,idx2]

array([ 8, 15, 12])

In [206]:
idx2

[3, 0, 2]

In [207]:
a[idx1]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14]])

## Subarrays of Numpy Arrays Affects Original Array !

In [208]:
a = np.arange(1,21).reshape(4,5)

In [209]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [210]:
b = a[:2,:3]

In [211]:
b

array([[1, 2, 3],
       [6, 7, 8]])

In [212]:
b.ndim

2

In [213]:
b[0,0] = 100

In [214]:
b

array([[100,   2,   3],
       [  6,   7,   8]])

In [215]:
a

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

## Copy

>To solve above problem we will use copy()

In [216]:
a = np.arange(1,21).reshape(4,5)

In [217]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [218]:
b = a[:2,:3].copy()

In [219]:
b

array([[1, 2, 3],
       [6, 7, 8]])

In [220]:
b[0,0] = 100

In [221]:
b

array([[100,   2,   3],
       [  6,   7,   8]])

In [222]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## Fancy Indexing

In [223]:
x = np.arange(1,15)

In [224]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [225]:
idxs = [4,5,6]

In [226]:
# It will return the elements at 4 5 6
x[idxs]

array([5, 6, 7])

In [227]:
a = np.arange(12).reshape(3,4)

In [228]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [229]:
a[0:2,1:3]

array([[1, 2],
       [5, 6]])

In [230]:
x = np.arange(9)

In [231]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [233]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [234]:
x[[1,2,3]] = 20

In [235]:
x

array([ 0, 20, 20, 20,  4,  5,  6,  7,  8])

In [236]:
x = np.arange(9)

In [237]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [238]:
x[[1,2,3]] = [100, 200, 300]

In [239]:
x

array([  0, 100, 200, 300,   4,   5,   6,   7,   8])

In [240]:
t = (1,2,3,4,5,6)

In [241]:
t

(1, 2, 3, 4, 5, 6)

In [242]:
t[3]

4

In [243]:
t = (1,2,3)


In [244]:
x[[1,2,3]]


array([100, 200, 300])

In [245]:
t = (1,2,3,4,5,6)

In [246]:
t[2:4]

(3, 4)

## Conditional Indexing

In [247]:
a = np.arange(1,10)

In [248]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [249]:
a < 5

array([ True,  True,  True,  True, False, False, False, False, False])

In [250]:
a[a<5]

array([1, 2, 3, 4])

In [251]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [252]:
filt = a < 3

In [253]:
a[filt]

array([1, 2])

In [254]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [255]:
b = np.array([2,3,3,4,5,61,7,8,11])

In [256]:
b

array([ 2,  3,  3,  4,  5, 61,  7,  8, 11])

In [257]:
a == b

array([False, False,  True,  True,  True, False,  True,  True, False])

In [258]:
a[a==b]

array([3, 4, 5, 7, 8])

In [259]:
b[a==b]

array([3, 4, 5, 7, 8])

In [260]:
# broadcasting
a == [1]

array([ True, False, False, False, False, False, False, False, False])

In [261]:
a == 1

array([ True, False, False, False, False, False, False, False, False])

In [262]:
a == 1

array([ True, False, False, False, False, False, False, False, False])

In [263]:
(-2 > 0) and (print("hey"))

False

In [264]:
(a < 3) | (a > 5)

array([ True,  True, False, False, False,  True,  True,  True,  True])

In [265]:
a[(a<3) | (a>5)]

array([1, 2, 6, 7, 8, 9])

In [266]:
filt = (a < 3) | (a > 5)

In [267]:
filt

array([ True,  True, False, False, False,  True,  True,  True,  True])

In [268]:
a[filt]

array([1, 2, 6, 7, 8, 9])

In [269]:
a[(a>3) & (a<=5)]

array([4, 5])

## In Multidimensional Arrays

In [270]:
a = np.arange(1,21).reshape(4,5)

In [271]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [272]:
type(a)

numpy.ndarray

In [273]:
type(a < 7)

numpy.ndarray

In [274]:
a < 7

array([[ True,  True,  True,  True,  True],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [275]:
a[a<7]

array([1, 2, 3, 4, 5, 6])

In [276]:
a[a<7].shape

(6,)

In [277]:
a = np.array([1,2,3,None])

In [278]:
a

array([1, 2, 3, None], dtype=object)

In [279]:
a==None

array([False, False, False,  True])

In [280]:
a[a==None]

array([None], dtype=object)

## sum()

>Finding how many elements satisfied given condition



In [281]:
a = np.arange(1,21).reshape(4,5)

In [282]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [283]:
np.sum(a)

210

In [284]:
filt = a < 5

In [285]:
filt

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [286]:
np.sum(filt)

4

In [287]:
a[filt]

array([1, 2, 3, 4])

In [288]:
np.sum(a[filt])

10

In [289]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [290]:
a[filt]

array([1, 2, 3, 4])

In [291]:

filt = (a>5) & (a<9)

In [292]:
np.sum(filt)

3

In [293]:
a[filt]

array([6, 7, 8])

In [294]:
np.sum(a[(a>5) & (a<9)])

21

In [295]:
filt

array([[False, False, False, False, False],
       [ True,  True,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [296]:
~((a>5) & (a<9))

array([[ True,  True,  True,  True,  True],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [297]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [298]:
filt = ~((a>5) & (a<9))

In [299]:
a[filt]

array([ 1,  2,  3,  4,  5,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [300]:
np.sum(~((a>5) & (a<9)))

17

In [301]:
np.sum(a[~((a>5) & (a<9))])

189

### Just sum of the Specified Axis

In [302]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])

In [303]:
np.concatenate([x, x], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [304]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [305]:
np.sum(a, axis = 0)

array([34, 38, 42, 46, 50])

In [306]:
np.sum(a, axis = 1)

array([15, 40, 65, 90])

In [307]:
np.sum((a>5) & (a<9))

3

In [308]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [309]:
(a>5) & (a<9)

array([[False, False, False, False, False],
       [ True,  True,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [310]:
np.sum((a>5) & (a<9), axis = 0)

array([1, 1, 1, 0, 0])

In [311]:
np.sum(a[(a>5) & (a<9)])

21

In [312]:
np.sum((a>5) & (a<9), axis = 1)

array([0, 3, 0, 0])

## all()

>Checking if all elements satisfies given condition

In [313]:
a = np.arange(20).reshape(4,5)


In [314]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [315]:
a > 5

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [316]:

np.sum(a>5, axis = 1)

array([0, 4, 5, 5])

In [317]:
a<-1

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [318]:
a>-1

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [319]:
np.all(a>-1)

True

In [320]:
filt = a > -1

In [321]:
np.all(filt)

True

In [323]:
np.all(a>-1, axis = 1)

array([ True,  True,  True,  True])

In [324]:
np.all(a>-1, axis = 0)

array([ True,  True,  True,  True,  True])

In [325]:
a>4

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [327]:
np.all(a>4)

False

In [328]:
np.all(a>4, axis = 1)

array([False,  True,  True,  True])

np.all(a>4, axis = 0)

## any()

>Checking if there is any element satisfying this condition

In [330]:
a = np.arange(20).reshape(4,5)

In [331]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [332]:
a>17

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True]])

In [333]:
np.any(a>17)

True

In [335]:
np.any(a>17,axis = 0)

array([False, False, False,  True,  True])

In [336]:
np.any(a>17,axis = 1)

array([False, False, False,  True])

## Some Numpy Functions

In [337]:
x = np.random.normal(0, 1, 40).reshape(8,5)

In [338]:
x = np.random.normal(0, 1,(8,5))

In [339]:
x

array([[ 0.72857371, -0.07926495, -0.35389598,  0.85810714, -0.66922423],
       [ 0.25636199,  1.3251312 ,  0.38935576,  1.06671286, -1.86112902],
       [-0.91112351, -0.13192616,  1.463011  , -1.71955229,  1.01980806],
       [-2.12810571,  2.16833189,  0.97735535, -0.45708892,  1.47439901],
       [ 1.32018829, -1.27640503,  0.04692622,  0.84118019, -0.89908987],
       [-0.00514276,  1.01472998, -0.32777359,  1.02959175, -0.24491857],
       [-1.09972366,  1.84037473,  0.78747234,  0.02077722,  0.45733261],
       [-0.12395843,  0.19651181,  0.22962068, -0.07589939,  0.15351407]])

In [340]:
x.ndim

2

In [341]:
np.mean(x)

0.18252864558038934

In [342]:
np.mean(x, axis = 0)

array([-0.24536626,  0.63218544,  0.40150897,  0.19547857, -0.07116349])

In [343]:
np.mean(x, axis = 1)

array([ 0.09685914,  0.23528656, -0.05595658,  0.40697832,  0.00655996,
        0.29329736,  0.40124665,  0.07595775])

In [344]:
np.std(x)

0.9918634231322643

In [345]:
np.std(x, axis = 0)

array([1.02722719, 1.08215865, 0.59846316, 0.90195311, 1.01156294])

In [346]:
np.var(x)

0.9837930501476532

In [347]:
np.median(x)

0.1750129419732163

In [348]:
sum(x)

array([-1.96293008,  5.05748348,  3.21207178,  1.56382858, -0.56930793])

In [349]:
np.max(x)


2.168331892274122

In [350]:
np.min(x)


-2.1281057086390356

## Numpy Functions on Multidimensional Arrays


In [351]:
x = np.random.normal(0, 1, (4,4))

In [352]:
x

array([[ 0.59096715,  0.04018718,  0.84919915,  1.09923443],
       [ 1.00860849,  0.77609528, -1.48383116,  0.27399322],
       [ 0.22655708, -0.01462509, -0.32973372, -0.09471306],
       [ 0.44018333,  1.28111323,  0.33923874,  0.04226889]])

In [353]:
x.sum()

5.044743146174582

In [354]:
x.sum(axis = 0)

array([ 2.26631605,  2.0827706 , -0.62512698,  1.32078348])

In [355]:
x.sum(axis = 1)

array([ 2.57958791,  0.57486583, -0.21251479,  2.10280419])

In [357]:
x.mean()

0.3152964466359114

In [358]:
x[0]

array([0.59096715, 0.04018718, 0.84919915, 1.09923443])

In [359]:
x.mean(axis = 1)

array([ 0.64489698,  0.14371646, -0.0531287 ,  0.52570105])

In [360]:
x[0].mean()

0.6448969783649453

In [361]:
x.mean(axis = 1)

array([ 0.64489698,  0.14371646, -0.0531287 ,  0.52570105])

## Broadcasting

In [362]:
a = np.array([1,2,3,4])

In [363]:
b = np.array([[1,2,3,4],
             [5,6,7,8]])

In [364]:
a

array([1, 2, 3, 4])

In [365]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [366]:
a.ndim

1

In [367]:
b.ndim

2

In [368]:
a.shape

(4,)

In [369]:
b.shape

(2, 4)

In [370]:
a

array([1, 2, 3, 4])

In [371]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [372]:
a + b

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12]])

In [373]:

c = np.arange(4).reshape(4,1)

In [374]:
c

array([[0],
       [1],
       [2],
       [3]])

In [375]:
a

array([1, 2, 3, 4])

In [376]:
a + c

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])